return {
    Order = 10, 
    DisplayName = "ANIME", 
    Price = 3000, 
    ImageId = 130445813492636, 
    GlowColor = Color3.fromRGB(230, 32, 32), 
    BackgroundColor = Color3.fromRGB(217, 20, 24), 
    FrameColor = Color3.fromRGB(36, 10, 10), 
    Unusuals = {
        "Fox", 
        "Legendary", 
        "Instinct", 
        "Black Flash", 
        "Ripple"
    }, 
    Drops = {
        "Slayer", 
        "Ninja", 
        "Alchemist", 
        "Sukuna", 
        "Kurta", 
        "Pantera", 
        "Ghoul", 
        "Super", 
        "Chainsaw", 
        "Berserk"
    }, 
    Rates = {
        Uncommon = 65.5, 
        Rare = 27, 
        Mythic = 6, 
        Legendary = 1.5, 
        Unusual = 1
    }
};