return {
    Lighting = {
        Ambient = Color3.fromRGB(0, 0, 0), 
        Brightness = 4.66, 
        ColorShift_Bottom = Color3.fromRGB(0, 0, 0), 
        ColorShift_Top = Color3.fromRGB(0, 0, 0), 
        EnvironmentDiffuseScale = 0, 
        EnvironmentSpecularScale = 0.379, 
        OutdoorAmbient = Color3.fromRGB(200, 60, 218), 
        ShadowSoftness = 0.2, 
        ClockTime = 11.4, 
        GeographicLatitude = 0, 
        ExposureCompensation = 0.05
    }
};