return {
    {
        Type = "Spins", 
        Amount = 5
    }, 
    {
        Type = "Spins", 
        Amount = 7
    }, 
    {
        Type = "Cash", 
        Amount = 7500
    }, 
    {
        Type = "Emote", 
        Amount = 1, 
        UIStroke = "Mythic"
    }, 
    {
        Type = "Spins", 
        Amount = 10
    }, 
    {
        Type = "Cash", 
        Amount = 10000
    }, 
    {
        Type = "LuckySpins", 
        Amount = 3, 
        Target = true
    }, 
    {
        Type = "Cash", 
        Amount = 12500
    }, 
    {
        Type = "Emote", 
        Amount = 1, 
        UIStroke = "Mythic"
    }, 
    {
        Type = "Spins", 
        Amount = 10
    }, 
    {
        Type = "Cash", 
        Amount = 12500
    }, 
    {
        Type = "Emote", 
        Amount = 1, 
        UIStroke = "Mythic"
    }, 
    {
        Type = "Spins", 
        Amount = 12
    }, 
    {
        Type = "MaxPity", 
        Amount = 1, 
        Target = true
    }, 
    {
        Type = "LuckyCrates", 
        Amount = 3
    }, 
    {
        Type = "Spins", 
        Amount = 15
    }, 
    {
        Type = "LuckySpins", 
        Amount = 3
    }, 
    {
        Type = "Cash", 
        Amount = 17500
    }, 
    {
        Type = "Spins", 
        Amount = 17
    }, 
    {
        Type = "Cash", 
        Amount = 20000
    }, 
    {
        Type = "LuckyCrates", 
        Amount = 3
    }, 
    {
        Type = "Spins", 
        Amount = 20
    }, 
    {
        Type = "Cash", 
        Amount = 25000
    }, 
    {
        Type = "Emote", 
        Amount = 1, 
        UIStroke = "Mythic"
    }, 
    {
        Type = "Spins", 
        Amount = 25
    }, 
    {
        Type = "Cash", 
        Amount = 25000
    }, 
    {
        Type = "LuckySpins", 
        Amount = 10
    }, 
    {
        Type = "LuckyCrates", 
        Amount = 5
    }, 
    {
        Type = "Emote", 
        Amount = 1, 
        UIStroke = "Mythic"
    }, 
    {
        Type = "Slot", 
        Amount = 1, 
        Target = true
    }
};