return {
    {
        Type = "Spins", 
        Amount = 10
    }, 
    {
        Type = "LuckySpins", 
        Amount = 3
    }, 
    {
        Type = "Spins", 
        Amount = 15
    }, 
    {
        Type = "Cash", 
        Amount = 15000
    }, 
    {
        Type = "Spins", 
        Amount = 15
    }, 
    {
        Type = "MaxPity", 
        Amount = 1, 
        Target = true
    }, 
    {
        Type = "Emote", 
        Amount = 1, 
        UIStroke = "Mythic"
    }, 
    {
        Type = "LuckyCrates", 
        Amount = 3
    }, 
    {
        Type = "Cash", 
        Amount = 15000
    }, 
    {
        Type = "Spins", 
        Amount = 15
    }, 
    {
        Type = "LuckyCrates", 
        Amount = 3
    }, 
    {
        Type = "Spins", 
        Amount = 20
    }, 
    {
        Type = "Emote", 
        Amount = 1, 
        UIStroke = "Mythic"
    }, 
    {
        Type = "LuckySpins", 
        Amount = 10, 
        Target = true
    }, 
    {
        Type = "Cash", 
        Amount = 15000
    }, 
    {
        Type = "Spins", 
        Amount = 10
    }, 
    {
        Type = "Cash", 
        Amount = 20000
    }, 
    {
        Type = "Emote", 
        Amount = 1, 
        UIStroke = "Mythic"
    }, 
    {
        Type = "Spins", 
        Amount = 15
    }, 
    {
        Type = "Cash", 
        Amount = 25000
    }, 
    {
        Type = "Emote", 
        Amount = 1, 
        UIStroke = "Mythic"
    }, 
    {
        Type = "LuckyCrates", 
        Amount = 3
    }, 
    {
        Type = "Spins", 
        Amount = 20
    }, 
    {
        Type = "Cash", 
        Amount = 30000
    }, 
    {
        Type = "Emote", 
        Amount = 1, 
        UIStroke = "Mythic"
    }, 
    {
        Type = "Spins", 
        Amount = 25
    }, 
    {
        Type = "LuckySpins", 
        Amount = 5
    }, 
    {
        Type = "LuckyCrates", 
        Amount = 3
    }, 
    {
        Type = "Emote", 
        Amount = 1, 
        UIStroke = "Mythic"
    }, 
    {
        Type = "Slot", 
        Amount = 1, 
        Target = true
    }
};