local v0 = {
    ["Void Apostle"] = {
        Quality = 666
    }, 
    Boxer = {
        Quality = 0
    }, 
    Puncher = {
        Quality = 1, 
        Type = "Knockdowns", 
        Amount = 5
    }, 
    Powerful = {
        Quality = 2, 
        Type = "Knockdowns", 
        Amount = 10
    }, 
    ["Heavy Hitter"] = {
        Quality = 2, 
        Type = "Knockdowns", 
        Amount = 25
    }, 
    Assassin = {
        Quality = 3, 
        Type = "Knockdowns", 
        Amount = 50
    }, 
    ["Lights Out"] = {
        Quality = 4, 
        Type = "Knockdowns", 
        Amount = 75
    }, 
    Hurricane = {
        Quality = 4, 
        Type = "Knockdowns", 
        Amount = 100
    }, 
    Rampage = {
        Quality = 5, 
        Type = "Knockdowns", 
        Amount = 150
    }, 
    Executioner = {
        Quality = 5, 
        Type = "Knockdowns", 
        Amount = 225
    }, 
    Shotgun = {
        Quality = 6, 
        Type = "Knockdowns", 
        Amount = 350
    }, 
    ["The Hawk"] = {
        Quality = 6, 
        Type = "Knockdowns", 
        Amount = 650
    }, 
    ["Touch of Death"] = {
        Quality = 7, 
        Type = "Knockdowns", 
        Amount = 1000
    }, 
    Tank = {
        Quality = 7, 
        Type = "Knockdowns", 
        Amount = 1500
    }, 
    Monster = {
        Quality = 8, 
        Type = "Knockdowns", 
        Amount = 2500
    }, 
    ["Hands of Stone"] = {
        Quality = 9, 
        Type = "Knockdowns", 
        Amount = 5000
    }, 
    Iron = {
        Quality = 10, 
        Type = "Knockdowns", 
        Amount = 10000
    }, 
    ["Streak Hunter"] = {
        Quality = 2, 
        Type = "HighestTaken", 
        Amount = 10
    }, 
    Nightmare = {
        Quality = 3, 
        Type = "HighestTaken", 
        Amount = 25
    }, 
    Merciless = {
        Quality = 4, 
        Type = "HighestTaken", 
        Amount = 100
    }, 
    ["The Reaper"] = {
        Quality = 5, 
        Type = "HighestTaken", 
        Amount = 200, 
        DisplayTitle = "Reaper"
    }, 
    Heartbreaker = {
        Quality = 6, 
        Type = "HighestTaken", 
        Amount = 350
    }, 
    Bodysnatcher = {
        Quality = 7, 
        Type = "HighestTaken", 
        Amount = 500
    }, 
    ["El Cucuy"] = {
        Quality = 8, 
        Type = "HighestTaken", 
        Amount = 1000
    }, 
    Hitman = {
        Quality = 9, 
        Type = "HighestTaken", 
        Amount = 2500
    }, 
    Surging = {
        Quality = 1, 
        Type = "HighestStreak", 
        Amount = 3
    }, 
    Unrivaled = {
        Quality = 2, 
        Type = "HighestStreak", 
        Amount = 5
    }, 
    Immortal = {
        Quality = 3, 
        Type = "HighestStreak", 
        Amount = 10
    }, 
    ["The Real Deal"] = {
        Quality = 4, 
        Type = "HighestStreak", 
        Amount = 25
    }, 
    Marvelous = {
        Quality = 5, 
        Type = "HighestStreak", 
        Amount = 50
    }, 
    ["The Takeover"] = {
        Quality = 6, 
        Type = "HighestStreak", 
        Amount = 75
    }, 
    ["The Last Emperor"] = {
        Quality = 7, 
        Type = "HighestStreak", 
        Amount = 150
    }, 
    Sugar = {
        Quality = 8, 
        Type = "HighestStreak", 
        Amount = 250
    }, 
    Legend = {
        Quality = 9, 
        Type = "HighestStreak", 
        Amount = 500
    }, 
    ["El Finito"] = {
        Quality = 10, 
        Type = "HighestStreak", 
        Amount = 750
    }, 
    ["The Greatest"] = {
        Quality = 10, 
        Type = "HighestStreak", 
        Amount = 1500
    }, 
    Smooth = {
        Quality = 1, 
        Type = "Defended", 
        Amount = 100
    }, 
    Untouchable = {
        Quality = 2, 
        Type = "Defended", 
        Amount = 500
    }, 
    ["Rope-a-Dope"] = {
        Quality = 4, 
        Type = "Defended", 
        Amount = 2000
    }, 
    ["Sweet Pea"] = {
        Quality = 5, 
        Type = "Defended", 
        Amount = 5000
    }, 
    Prince = {
        Quality = 6, 
        Type = "Defended", 
        Amount = 10000
    }, 
    ["The Old Mongoose"] = {
        Quality = 8, 
        Type = "Defended", 
        Amount = 20000
    }, 
    ["The Grandmaster"] = {
        Quality = 9, 
        Type = "Defended", 
        Amount = 50000
    }, 
    ["Can\226\128\153t Be Touched"] = {
        Quality = 10, 
        Type = "Defended", 
        Amount = 100000
    }, 
    Speedy = {
        Quality = 1, 
        Type = "PunchesThrown", 
        Amount = 250
    }, 
    Swift = {
        Quality = 2, 
        Type = "PunchesThrown", 
        Amount = 500
    }, 
    ["The Flash"] = {
        Quality = 3, 
        Type = "PunchesThrown", 
        Amount = 1000
    }, 
    Sniper = {
        Quality = 4, 
        Type = "PunchesThrown", 
        Amount = 2500
    }, 
    Raging = {
        Quality = 6, 
        Type = "PunchesThrown", 
        Amount = 10000
    }, 
    Mayhem = {
        Quality = 7, 
        Type = "PunchesThrown", 
        Amount = 25000
    }, 
    ["The Machine"] = {
        Quality = 8, 
        Type = "PunchesThrown", 
        Amount = 50000
    }, 
    Rush = {
        Quality = 9, 
        Type = "PunchesThrown", 
        Amount = 100000
    }, 
    Rocky = {
        Quality = 10, 
        Type = "PunchesThrown", 
        Amount = 500000
    }, 
    Fighting = {
        Quality = 1, 
        Type = "UltimatesLanded", 
        Amount = 5
    }, 
    Punisher = {
        Quality = 2, 
        Type = "UltimatesLanded", 
        Amount = 10
    }, 
    Overkill = {
        Quality = 4, 
        Type = "UltimatesLanded", 
        Amount = 30
    }, 
    ["The Dragon"] = {
        Quality = 6, 
        Type = "UltimatesLanded", 
        Amount = 75
    }, 
    Showtime = {
        Quality = 7, 
        Type = "UltimatesLanded", 
        Amount = 250
    }, 
    ["The Highlight"] = {
        Quality = 9, 
        Type = "UltimatesLanded", 
        Amount = 500
    }, 
    Ultimate = {
        Quality = 10, 
        Type = "UltimatesLanded", 
        Amount = 1000
    }, 
    Golden = {
        Quality = 4, 
        Type = "CashEarned", 
        Amount = 25000
    }, 
    Notorious = {
        Quality = 7, 
        Type = "CashEarned", 
        Amount = 100000
    }, 
    Money = {
        Quality = 10, 
        Type = "CashEarned", 
        Amount = 1000000
    }, 
    Technician = {
        Quality = 1, 
        Type = "PerfectDodges", 
        Amount = 5
    }, 
    ["Wind God"] = {
        Quality = 4, 
        Type = "PerfectDodges", 
        Amount = 50
    }, 
    Ghost = {
        Quality = 7, 
        Type = "PerfectDodges", 
        Amount = 250
    }, 
    Perfect = {
        Quality = 8, 
        Type = "PerfectDodges", 
        Amount = 500
    }, 
    ["Ultra Instinct"] = {
        Quality = 9, 
        Type = "PerfectDodges", 
        Amount = 3000
    }, 
    Counterpuncher = {
        Quality = 1, 
        Type = "Counters", 
        Amount = 5
    }, 
    ["Counter Demon"] = {
        Quality = 2, 
        Type = "Counters", 
        Amount = 20
    }, 
    ["Lightning God"] = {
        Quality = 5, 
        Type = "Counters", 
        Amount = 100
    }, 
    ["Counter King"] = {
        Quality = 7, 
        Type = "Counters", 
        Amount = 300
    }, 
    ["El Chacal"] = {
        Quality = 8, 
        Type = "Counters", 
        Amount = 1000
    }, 
    ["Tomorrow's Joe"] = {
        Quality = 9, 
        Type = "Counters", 
        Amount = 10000
    }, 
    Artist1 = {
        Quality = 20, 
        DisplayTitle = "Artist \240\159\142\168"
    }, 
    Artist2 = {
        Quality = 20, 
        DisplayTitle = "my art is in game"
    }, 
    BalanceTeam = {
        Quality = 100, 
        DisplayTitle = "Balance Team"
    }, 
    StaffTeam = {
        Quality = 101, 
        DisplayTitle = "Official Staff"
    }, 
    crazyguy = {
        Quality = 101, 
        DisplayTitle = "oh god i love traffic cones i have so many at home they r my favorite thing everlook at the colorit has sparkles on iti feel like i saw one todayoutside of my housethere was a red onesparkles on itlike big onesi dont know where it came fromit was just sitting thereit doesnt matteri would steal thatcone if i could. im gonna hug myself i just wanted to talk to someoneand i wanted to talk about traffic conesbut now its all i can think aboutand i hate themi feel like i am going insaneits not normal idk why its so funny. i really dolove traffic cones butnobody else listenssomeone please talkto me aboutmy traffic cones ihave it was glowing like crazy i picked it up and it disappearedand i got so upset and i cried and cried and cried and cried and cried until i foundit again and returned it homewell i returned it to my home i took it its mine"
    }, 
    uba_s1 = {
        Quality = 999, 
        DisplayTitle = "UBA World Champion (S1)"
    }
};
local l_SeasonHelper_0 = require(game.ReplicatedFirst:WaitForChild("SeasonHelper"));
local v2 = l_SeasonHelper_0.GetCurrentSeason();
local function v8(v3) --[[ Line: 515 ]] --[[ Name: GetSeasonTitles ]]
    -- upvalues: v2 (copy), v0 (copy)
    for _, v5 in v3 do
        local l_Title_0 = v5.Title;
        if l_Title_0 then
            for v7 = 1, v2 + 3 do
                v0[("%* (S%*)"):format(l_Title_0, (tostring(v7)))] = {
                    Quality = v5.Quality, 
                    Type = "Seasonal"
                };
            end;
        end;
    end;
end;
v8(l_SeasonHelper_0.KnockdownRewards);
v8(l_SeasonHelper_0.WinRewards);
for v9, v10 in require(game.ReplicatedStorage:WaitForChild("RankHelper")).RankInfo do
    v0[v9] = {
        Quality = v10.Quality, 
        Type = "Rank"
    };
end;
local l_Modules_0 = game:GetService("ReplicatedStorage"):WaitForChild("Modules");
for v12, v13 in (require(l_Modules_0:WaitForChild("Styles"))) do
    local l_Titles_0 = v13.Titles;
    if l_Titles_0 then
        for _, v16 in l_Titles_0 do
            local l_Name_0 = v16.Name;
            v16.Style = v12;
            v0[l_Name_0] = v16;
        end;
    end;
end;
return v0;