return {
    EffectsFolder = workspace.MeshSpawn, 
    Mesh_Properities = {
        SpecialMesh = {
            "Scale"
        }, 
        MeshPart = {
            "Size", 
            "Color", 
            "Transparency"
        }, 
        Decal = {
            "Transparency", 
            "Color3"
        }, 
        Highlight = {
            "FillColor", 
            "FillTransparency", 
            "OutlineColor", 
            "OutlineTransparency"
        }
    }
};