return {
    Lighting = {
        Ambient = Color3.fromRGB(0, 0, 0), 
        Brightness = 1.74, 
        ColorShift_Bottom = Color3.fromRGB(0, 0, 0), 
        ColorShift_Top = Color3.fromRGB(0, 0, 0), 
        EnvironmentDiffuseScale = 1, 
        EnvironmentSpecularScale = 1, 
        OutdoorAmbient = Color3.fromRGB(0, 0, 0), 
        ShadowSoftness = 0.2, 
        ClockTime = 13.5, 
        GeographicLatitude = 182, 
        ExposureCompensation = -2
    }
};