return {
    Settings = {
        Server = {
            "KickOnLoss", 
            "LockServer", 
            "RefreshServer"
        }, 
        Utility = {
            "InfiniteUltimate", 
            "InfiniteAbility"
        }, 
        Combat = {
            "WalkspeedMultiplier", 
            "DashMultiplier", 
            "LightAttackDamageMultiplier", 
            "HeavyAttackDamageMultiplier", 
            "LightAttackSpeedMultiplier", 
            "HeavyAttackSpeedMultiplier", 
            "PerfectDodgeWindow", 
            "UltimateChargeMultiplier", 
            "StunTimeMultiplier", 
            "HealthMultiplier", 
            "StaminaMultiplier", 
            "HitboxMultiplier", 
            "DisableFeints", 
            "MaxKnockdowns", 
            "AbilityMultiplier"
        }, 
        Match = {
            "ForceMatch", 
            "CreateRoundTimer", 
            "AddReferee", 
            "Storm", 
            "StormSpeedMultiplier", 
            "StormDamageMultiplier"
        }, 
        Movesets = {
            "RandomAbility", 
            "RandomUltimate"
        }, 
        NPCs = {
            "SpawnBlockingDummy", 
            "SpawnHeavyDummy", 
            "SpawnPunchingDummy", 
            "SpawnAggressiveDummy", 
            "SpawnDrowningsome", 
            "SetDummyStyle", 
            "ClearNPCs"
        }, 
        Miscellaneous = {
            "TrueBulletStyle"
        }
    }, 
    Categories = {
        "Server", 
        "Utility", 
        "Combat", 
        "Match", 
        "Movesets", 
        "NPCs", 
        "Miscellaneous"
    }
};