return {
    children = {
        {
            children = {
                {
                    children = {
                        {
                            children = {
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\BinarySearch-Features.lua"
                                    }, 
                                    name = "BinarySearch-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\BinarySearch.lua"
                                    }, 
                                    name = "BinarySearch"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\BinarySearch.spec.lua"
                                    }, 
                                    name = "BinarySearch.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Cut-Features.lua"
                                    }, 
                                    name = "Cut-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Cut.lua"
                                    }, 
                                    name = "Cut"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Cut.spec.lua"
                                    }, 
                                    name = "Cut.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Equals-Features.lua"
                                    }, 
                                    name = "Equals-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Equals.lua"
                                    }, 
                                    name = "Equals"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Equals.spec.lua"
                                    }, 
                                    name = "Equals.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Filter-Features.lua"
                                    }, 
                                    name = "Filter-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Filter.lua"
                                    }, 
                                    name = "Filter"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Filter.spec.lua"
                                    }, 
                                    name = "Filter.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\FoldLeft-Features.lua"
                                    }, 
                                    name = "FoldLeft-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\FoldLeft.lua"
                                    }, 
                                    name = "FoldLeft"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\FoldLeft.spec.lua"
                                    }, 
                                    name = "FoldLeft.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\FoldRight-Features.lua"
                                    }, 
                                    name = "FoldRight-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\FoldRight.lua"
                                    }, 
                                    name = "FoldRight"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\FoldRight.spec.lua"
                                    }, 
                                    name = "FoldRight.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\GroupBy-Features.lua"
                                    }, 
                                    name = "GroupBy-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\GroupBy.lua"
                                    }, 
                                    name = "GroupBy"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\GroupBy.spec.lua"
                                    }, 
                                    name = "GroupBy.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Insert-Features.lua"
                                    }, 
                                    name = "Insert-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Insert.lua"
                                    }, 
                                    name = "Insert"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Insert.spec.lua"
                                    }, 
                                    name = "Insert.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\IsOrdered-Features.lua"
                                    }, 
                                    name = "IsOrdered-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\IsOrdered.lua"
                                    }, 
                                    name = "IsOrdered"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\IsOrdered.spec.lua"
                                    }, 
                                    name = "IsOrdered.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Map-Features.lua"
                                    }, 
                                    name = "Map-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Map.lua"
                                    }, 
                                    name = "Map"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Map.spec.lua"
                                    }, 
                                    name = "Map.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Mean-Features.lua"
                                    }, 
                                    name = "Mean-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Mean.lua"
                                    }, 
                                    name = "Mean"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Mean.spec.lua"
                                    }, 
                                    name = "Mean.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Merge-Features.lua"
                                    }, 
                                    name = "Merge-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Merge.lua"
                                    }, 
                                    name = "Merge"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Merge.spec.lua"
                                    }, 
                                    name = "Merge.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MergeMany-Features.lua"
                                    }, 
                                    name = "MergeMany-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MergeMany.lua"
                                    }, 
                                    name = "MergeMany"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MergeMany.spec.lua"
                                    }, 
                                    name = "MergeMany.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableBinaryInsert-Features.lua"
                                    }, 
                                    name = "MutableBinaryInsert-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableBinaryInsert.lua"
                                    }, 
                                    name = "MutableBinaryInsert"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableBinaryInsert.spec.lua"
                                    }, 
                                    name = "MutableBinaryInsert.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableMerge-Feature.lua"
                                    }, 
                                    name = "MutableMerge-Feature"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableMerge.lua"
                                    }, 
                                    name = "MutableMerge"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableMerge.spec.lua"
                                    }, 
                                    name = "MutableMerge.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableMergeMany-Feature.lua"
                                    }, 
                                    name = "MutableMergeMany-Feature"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableMergeMany.lua"
                                    }, 
                                    name = "MutableMergeMany"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableMergeMany.spec.lua"
                                    }, 
                                    name = "MutableMergeMany.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableReverse-Features.lua"
                                    }, 
                                    name = "MutableReverse-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableReverse.lua"
                                    }, 
                                    name = "MutableReverse"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableReverse.spec.lua"
                                    }, 
                                    name = "MutableReverse.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableShuffle-Features.lua"
                                    }, 
                                    name = "MutableShuffle-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableShuffle.lua"
                                    }, 
                                    name = "MutableShuffle"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\MutableShuffle.spec.lua"
                                    }, 
                                    name = "MutableShuffle.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Percentile-Features.lua"
                                    }, 
                                    name = "Percentile-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Percentile.lua"
                                    }, 
                                    name = "Percentile"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Percentile.spec.lua"
                                    }, 
                                    name = "Percentile.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Product-Features.lua"
                                    }, 
                                    name = "Product-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Product.lua"
                                    }, 
                                    name = "Product"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Product.spec.lua"
                                    }, 
                                    name = "Product.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Range-Features.lua"
                                    }, 
                                    name = "Range-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Range.lua"
                                    }, 
                                    name = "Range"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Range.spec.lua"
                                    }, 
                                    name = "Range.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Remove-Features.lua"
                                    }, 
                                    name = "Remove-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Remove.lua"
                                    }, 
                                    name = "Remove"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Remove.spec.lua"
                                    }, 
                                    name = "Remove.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\RemoveRange-Features.lua"
                                    }, 
                                    name = "RemoveRange-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\RemoveRange.lua"
                                    }, 
                                    name = "RemoveRange"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\RemoveRange.spec.lua"
                                    }, 
                                    name = "RemoveRange.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Reverse-Features.lua"
                                    }, 
                                    name = "Reverse-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Reverse.lua"
                                    }, 
                                    name = "Reverse"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Reverse.spec.lua"
                                    }, 
                                    name = "Reverse.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\SelectFirst-Features.lua"
                                    }, 
                                    name = "SelectFirst-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\SelectFirst.lua"
                                    }, 
                                    name = "SelectFirst"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\SelectFirst.spec.lua"
                                    }, 
                                    name = "SelectFirst.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\SelectLast-Features.lua"
                                    }, 
                                    name = "SelectLast-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\SelectLast.lua"
                                    }, 
                                    name = "SelectLast"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\SelectLast.spec.lua"
                                    }, 
                                    name = "SelectLast.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\SelectRandom-Features.lua"
                                    }, 
                                    name = "SelectRandom-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\SelectRandom.lua"
                                    }, 
                                    name = "SelectRandom"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\SelectRandom.spec.lua"
                                    }, 
                                    name = "SelectRandom.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\SelectWeighted-Features.lua"
                                    }, 
                                    name = "SelectWeighted-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\SelectWeighted.lua"
                                    }, 
                                    name = "SelectWeighted"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\SelectWeighted.spec.lua"
                                    }, 
                                    name = "SelectWeighted.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Shuffle-Features.lua"
                                    }, 
                                    name = "Shuffle-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Shuffle.lua"
                                    }, 
                                    name = "Shuffle"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Shuffle.spec.lua"
                                    }, 
                                    name = "Shuffle.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Sort-Features.lua"
                                    }, 
                                    name = "Sort-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Sort.lua"
                                    }, 
                                    name = "Sort"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Sort.spec.lua"
                                    }, 
                                    name = "Sort.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Sum-Features.lua"
                                    }, 
                                    name = "Sum-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Sum.lua"
                                    }, 
                                    name = "Sum"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Array\\Sum.spec.lua"
                                    }, 
                                    name = "Sum.spec"
                                }
                            }, 
                            className = "ModuleScript", 
                            filePaths = {
                                "src\\Array\\init.lua"
                            }, 
                            name = "Array"
                        }, 
                        {
                            children = {
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Changes-Features.lua"
                                    }, 
                                    name = "Changes-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Changes.lua"
                                    }, 
                                    name = "Changes"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Changes.spec.lua"
                                    }, 
                                    name = "Changes.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\CloneDeep-Features.lua"
                                    }, 
                                    name = "CloneDeep-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\CloneDeep.lua"
                                    }, 
                                    name = "CloneDeep"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\CloneDeep.spec.lua"
                                    }, 
                                    name = "CloneDeep.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Count-Features.lua"
                                    }, 
                                    name = "Count-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Count.lua"
                                    }, 
                                    name = "Count"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Count.spec.lua"
                                    }, 
                                    name = "Count.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\CreatePatchDeep-Features.lua"
                                    }, 
                                    name = "CreatePatchDeep-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\CreatePatchDeep.lua"
                                    }, 
                                    name = "CreatePatchDeep"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\CreatePatchDeep.spec.lua"
                                    }, 
                                    name = "CreatePatchDeep.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Creations-Features.lua"
                                    }, 
                                    name = "Creations-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Creations.lua"
                                    }, 
                                    name = "Creations"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Creations.spec.lua"
                                    }, 
                                    name = "Creations.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Equals-Features.lua"
                                    }, 
                                    name = "Equals-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Equals.lua"
                                    }, 
                                    name = "Equals"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Equals.spec.lua"
                                    }, 
                                    name = "Equals.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Filter-Features.lua"
                                    }, 
                                    name = "Filter-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Filter.lua"
                                    }, 
                                    name = "Filter"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Filter.spec.lua"
                                    }, 
                                    name = "Filter.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Flatten-Features.lua"
                                    }, 
                                    name = "Flatten-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Flatten.lua"
                                    }, 
                                    name = "Flatten"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Flatten.spec.lua"
                                    }, 
                                    name = "Flatten.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\FromKeyValueArray-Features.lua"
                                    }, 
                                    name = "FromKeyValueArray-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\FromKeyValueArray.lua"
                                    }, 
                                    name = "FromKeyValueArray"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\FromKeyValueArray.spec.lua"
                                    }, 
                                    name = "FromKeyValueArray.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\GroupBy-Features.lua"
                                    }, 
                                    name = "GroupBy-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\GroupBy.lua"
                                    }, 
                                    name = "GroupBy"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\GroupBy.spec.lua"
                                    }, 
                                    name = "GroupBy.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Map-Features.lua"
                                    }, 
                                    name = "Map-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Map.lua"
                                    }, 
                                    name = "Map"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Map.spec.lua"
                                    }, 
                                    name = "Map.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Merge-Features.lua"
                                    }, 
                                    name = "Merge-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Merge.lua"
                                    }, 
                                    name = "Merge"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Merge.spec.lua"
                                    }, 
                                    name = "Merge.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MergeDeep-Features.lua"
                                    }, 
                                    name = "MergeDeep-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MergeDeep.lua"
                                    }, 
                                    name = "MergeDeep"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MergeDeep.spec.lua"
                                    }, 
                                    name = "MergeDeep.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MergeMany-Features.lua"
                                    }, 
                                    name = "MergeMany-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MergeMany.lua"
                                    }, 
                                    name = "MergeMany"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MergeMany.spec.lua"
                                    }, 
                                    name = "MergeMany.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MutableMerge-Features.lua"
                                    }, 
                                    name = "MutableMerge-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MutableMerge.lua"
                                    }, 
                                    name = "MutableMerge"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MutableMerge.spec.lua"
                                    }, 
                                    name = "MutableMerge.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MutableMergeDeep-Features.lua"
                                    }, 
                                    name = "MutableMergeDeep-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MutableMergeDeep.lua"
                                    }, 
                                    name = "MutableMergeDeep"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MutableMergeDeep.spec.lua"
                                    }, 
                                    name = "MutableMergeDeep.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MutableMergeMany-Features.lua"
                                    }, 
                                    name = "MutableMergeMany-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MutableMergeMany.lua"
                                    }, 
                                    name = "MutableMergeMany"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\MutableMergeMany.spec.lua"
                                    }, 
                                    name = "MutableMergeMany.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Removals-Features.lua"
                                    }, 
                                    name = "Removals-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Removals.lua"
                                    }, 
                                    name = "Removals"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\Removals.spec.lua"
                                    }, 
                                    name = "Removals.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\ToKeyValueArray-Features.lua"
                                    }, 
                                    name = "ToKeyValueArray-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\ToKeyValueArray.lua"
                                    }, 
                                    name = "ToKeyValueArray"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Map\\ToKeyValueArray.spec.lua"
                                    }, 
                                    name = "ToKeyValueArray.spec"
                                }
                            }, 
                            className = "ModuleScript", 
                            filePaths = {
                                "src\\Map\\init.lua"
                            }, 
                            name = "Map"
                        }, 
                        {
                            children = {
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Difference-Features.lua"
                                    }, 
                                    name = "Difference-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Difference.lua"
                                    }, 
                                    name = "Difference"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Difference.spec.lua"
                                    }, 
                                    name = "Difference.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Equals-Features.lua"
                                    }, 
                                    name = "Equals-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Equals.lua"
                                    }, 
                                    name = "Equals"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Equals.spec.lua"
                                    }, 
                                    name = "Equals.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\FromKeys-Features.lua"
                                    }, 
                                    name = "FromKeys-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\FromKeys.lua"
                                    }, 
                                    name = "FromKeys"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\FromKeys.spec.lua"
                                    }, 
                                    name = "FromKeys.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\FromValues-Features.lua"
                                    }, 
                                    name = "FromValues-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\FromValues.lua"
                                    }, 
                                    name = "FromValues"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\FromValues.spec.lua"
                                    }, 
                                    name = "FromValues.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Insert-Features.lua"
                                    }, 
                                    name = "Insert-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Insert.lua"
                                    }, 
                                    name = "Insert"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Insert.spec.lua"
                                    }, 
                                    name = "Insert.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Intersection-Features.lua"
                                    }, 
                                    name = "Intersection-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Intersection.lua"
                                    }, 
                                    name = "Intersection"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Intersection.spec.lua"
                                    }, 
                                    name = "Intersection.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\IsProperSubset-Features.lua"
                                    }, 
                                    name = "IsProperSubset-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\IsProperSubset.lua"
                                    }, 
                                    name = "IsProperSubset"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\IsProperSubset.spec.lua"
                                    }, 
                                    name = "IsProperSubset.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\IsSubset-Features.lua"
                                    }, 
                                    name = "IsSubset-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\IsSubset.lua"
                                    }, 
                                    name = "IsSubset"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\IsSubset.spec.lua"
                                    }, 
                                    name = "IsSubset.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Remove-Features.lua"
                                    }, 
                                    name = "Remove-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Remove.lua"
                                    }, 
                                    name = "Remove"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Remove.spec.lua"
                                    }, 
                                    name = "Remove.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\SymmetricDifference-Features.lua"
                                    }, 
                                    name = "SymmetricDifference-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\SymmetricDifference.lua"
                                    }, 
                                    name = "SymmetricDifference"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\SymmetricDifference.spec.lua"
                                    }, 
                                    name = "SymmetricDifference.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\ToArray-Features.lua"
                                    }, 
                                    name = "ToArray-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\ToArray.lua"
                                    }, 
                                    name = "ToArray"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\ToArray.spec.lua"
                                    }, 
                                    name = "ToArray.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Union-Features.lua"
                                    }, 
                                    name = "Union-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Union.lua"
                                    }, 
                                    name = "Union"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\Union.spec.lua"
                                    }, 
                                    name = "Union.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\_DetectSet.lua"
                                    }, 
                                    name = "_DetectSet"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Set\\_SetType.lua"
                                    }, 
                                    name = "_SetType"
                                }
                            }, 
                            className = "ModuleScript", 
                            filePaths = {
                                "src\\Set\\init.lua"
                            }, 
                            name = "Set"
                        }, 
                        {
                            children = {
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsArray-Features.lua"
                                    }, 
                                    name = "IsArray-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsArray.lua"
                                    }, 
                                    name = "IsArray"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsArray.spec.lua"
                                    }, 
                                    name = "IsArray.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsMap-Features.lua"
                                    }, 
                                    name = "IsMap-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsMap.lua"
                                    }, 
                                    name = "IsMap"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsMap.spec.lua"
                                    }, 
                                    name = "IsMap.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsMixed-Features.lua"
                                    }, 
                                    name = "IsMixed-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsMixed.lua"
                                    }, 
                                    name = "IsMixed"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsMixed.spec.lua"
                                    }, 
                                    name = "IsMixed.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsPureArray-Features.lua"
                                    }, 
                                    name = "IsPureArray-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsPureArray.lua"
                                    }, 
                                    name = "IsPureArray"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsPureArray.spec.lua"
                                    }, 
                                    name = "IsPureArray.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsPureMap-Features.lua"
                                    }, 
                                    name = "IsPureMap-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsPureMap.lua"
                                    }, 
                                    name = "IsPureMap"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsPureMap.spec.lua"
                                    }, 
                                    name = "IsPureMap.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\IsSet-Features.lua"
                                    }, 
                                    name = "IsSet-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\Keys-Features.lua"
                                    }, 
                                    name = "Keys-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\Keys.lua"
                                    }, 
                                    name = "Keys"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\Keys.spec.lua"
                                    }, 
                                    name = "Keys.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\Lockdown-Features.lua"
                                    }, 
                                    name = "Lockdown-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\Lockdown.lua"
                                    }, 
                                    name = "Lockdown"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\Lockdown.spec.lua"
                                    }, 
                                    name = "Lockdown.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\SetUnresizable-Features.lua"
                                    }, 
                                    name = "SetUnresizable-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\SetUnresizable.lua"
                                    }, 
                                    name = "SetUnresizable"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\SetUnresizable.spec.lua"
                                    }, 
                                    name = "SetUnresizable.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\SwapKeysValues-Features.lua"
                                    }, 
                                    name = "SwapKeysValues-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\SwapKeysValues.lua"
                                    }, 
                                    name = "SwapKeysValues"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\SwapKeysValues.spec.lua"
                                    }, 
                                    name = "SwapKeysValues.spec"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\Values-Features.lua"
                                    }, 
                                    name = "Values-Features"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\Values.lua"
                                    }, 
                                    name = "Values"
                                }, 
                                {
                                    className = "ModuleScript", 
                                    filePaths = {
                                        "src\\Shared\\Values.spec.lua"
                                    }, 
                                    name = "Values.spec"
                                }
                            }, 
                            className = "Folder", 
                            name = "Shared"
                        }, 
                        {
                            className = "ModuleScript", 
                            filePaths = {
                                "src\\init.spec.lua"
                            }, 
                            name = "init.spec"
                        }
                    }, 
                    className = "ModuleScript", 
                    filePaths = {
                        "src\\init.lua"
                    }, 
                    name = "TableUtil"
                }
            }, 
            className = "ReplicatedFirst", 
            name = "ReplicatedFirst"
        }
    }, 
    className = "DataModel", 
    filePaths = {
        "place.project.json"
    }, 
    name = "TableUtil"
};